name: Update Live Streams

on:
  schedule:
    - cron: '0 */2 * * *'  # 每两小时运行一次
  workflow_dispatch:  # 手动触发

jobs:
  update-live-streams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Live Stream Fetch Script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python fetch_live_streams.py

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Pull Latest Changes
        run: |
          git pull --rebase origin main || git rebase --abort

      - name: Commit and Push Changes
        run: |
          git add live_streams.txt
          git commit -m "Update live streams" || echo "No changes to commit"
          git push origin main || echo "Push failed due to conflicts"
