name: Check YouTube Live Streams

on:
  schedule:
    - cron: '0 */2 * * *'  # 每两小时运行一次
  workflow_dispatch:  # 手动触发

jobs:
  check_live_streams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch_live_streams script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python fetch_live_streams.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain)" ]; then
            git add live_streams.txt
            git commit -m "Update live streams"
            git pull --rebase
            git push
          else
            echo "No changes to commit"
 
