name: Fetch Live Streams

on:
  schedule:
    - cron: '0 */2 * * *'  # 每兩小時執行一次
  workflow_dispatch:

jobs:
  fetch_live_streams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client

      - name: Run live stream fetcher
        run: python fetch_live_streams.py

      - name: Commit and push live streams
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          git add live_streams.txt
          git commit -m 'Update live streams'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
