name: Run YouTube Live Stream Scraper

on:
  schedule:
    - cron: '0 */2 * * *'  # 每兩小時執行一次
  workflow_dispatch:  # 允許手動觸發工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt  # 確保路徑正確

    - name: Run live stream scraper
      run: |
        python live_stream.py
