name: YouTube Live Scraper

on:
  schedule:
    - cron: "0 */2 * * *"  # 每兩小時執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v3
      
      - name: 設定 Python 環境
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: 安裝依賴
        run: pip install requests

      - name: 安裝 ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y chromium-chromedriver
          pip install webdriver-manager

      - name: 執行爬蟲
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python youtube_live_scraper.py
      
      - name: 提交更新
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
    
          # 確保遠端倉庫是最新的
          git fetch origin main
          git reset --hard origin/main  # 這行確保同步遠端版本，避免衝突
    
          # 重新執行檔案變更
          git add live_streams.txt
          git commit -m "Update live streams" || echo "No changes to commit"
          git push



