name: YouTube Live Scraper

on:
  schedule:
    - cron: "0 */2 * * *"  # 每兩小時執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v3
      
      - name: 設定 Python 環境
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: 安裝 Python 依賴
        run: |
          pip install selenium requests beautifulsoup4 webdriver-manager

      - name: 安裝 Chrome 和 ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=/usr/bin/chromedriver" >> $GITHUB_ENV
      
      - name: 執行爬蟲
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python youtube_live_scraper.py
      
      - name: 提交更新
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
    
          git fetch origin main
          git reset --hard origin/main
          git pull --rebase
     
          touch live_streams.txt  # 確保檔案存在
          git add live_streams.txt || echo "No live_streams.txt to add"
    
          git commit -m "Update live streams" || echo "No changes to commit"
          git push || echo "No changes to push"

